site_name: SaxDocs
site_url: https://docs.saxobroko.com
repo_url: https://github.com/saxobroko/SaxDocs
repo_name: saxobroko/SaxDocs
edit_uri: tree/main/docs
copyright: >
  Copyright &copy; 2004 - 2024 Saxon Brooker

plugins:
  - search
  - awesome-pages
  - minify
  - git-revision-date-localized:
      type: timeago
      custom_format: "%d. %B %Y"
      timezone: Australia/Melbourne
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      enabled: true
      strict: true
  - section-index
  - autolinks
  - pub-minifier
  - privacy
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SaxonYourBro/
    - icon: fontawesome/brands/github
      link: https://github.com/saxobroko
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/Saxo_Broko
  alternate:
    - name: English
      link: / 
      lang: en
theme:
  name: 'material'
  language: en
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.share
    - toc.follow
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode